### ISSUE TITLE
[BUG] En/decoding of zero-encoded messages very broken

### ISSUE THREAD

**Issue by Catharianna** [FelixWolf/pyverse#2]
I see that this project is abandoned, just filing this so that if someone comes across it like my friend did they don't think this is a working project.

As far as I'm able to tell encoding and decoding messages works only just well enough for me to be able to get a simple bot running, but when I tried doing more advanced things like having the bot join group-chats nothing seemed to work right.

After a bit of work I managed to see that decoding messages zero-encoded messages is very broken, plus there are some issues with encoding. The following program does a basic test of all messages, by first encoding and then decoding them.

```python
#!/usr/bin/env python3

import traceback

from pyverse.packet import packet
from pyverse.llTypes import variable
from pyverse import messages

ok = 0
bad = 0
ok_z = 0
bad_z = 0

all_message_classes = [b for a, b in messages.message_lookup.items() if isinstance(a, int)]

# def pretty_dict(data):
#     return {k: (str(v) if not isinstance(v, variable) else str(v)[:-1])
#             for k, v in (data if isinstance(data, dict) else data[0] if len(data) else {}).items()}

# def pretty_body(body):
#     return {k: pretty_dict(getattr(body, k)) for k in body.structure.keys()}

for msg_cls in all_message_classes:
    test_msg = msg_cls()

    pkg_raw = packet(message=test_msg) # No 'try' for this, haven't seen it raise any exception

    try:
        the_bytes = bytes(pkg_raw)
    except Exception as ex:
        print(f'BYTES ERROR: {msg_cls.name}{"(z)" if test_msg.zero_coded else "(not z)"}: {ex}')
        # traceback.print_exc()
        bad += 1
        if test_msg.zero_coded:
            bad_z += 1
        continue

    try:
        pkg_back = packet(data=the_bytes)
        print(f'OK: {pkg_back.body.name}{"(z)" if pkg_back.zero_coded else "(not z)"}')
        # print(f'OK: {pkg_back.body.name}{"(z)" if pkg_back.zero_coded else "(not z)"}: {pretty_body(pkg_back.body)}')
        ok += 1
        if test_msg.zero_coded:
            ok_z += 1
    except Exception as ex:
        print(f'DECODE ERROR: {msg_cls.name}{"(z)" if test_msg.zero_coded else "(not z)"}: {ex}')
        traceback.print_exc()
        bad += 1
        if test_msg.zero_coded:
            bad_z += 1
        continue


print(f'Number of OK messages: {ok}; of those zero-coded: {ok_z}; number of messages that failed to transcode: {bad}; of those zero-coded: {bad_z}')
```

When I run this in the pyverse root the result is:
```Number of OK messages: 290; of those zero-coded: 6; number of messages that failed to transcode: 185; of those zero-coded: 181```

Most zero-coded messages fail with a trace like the following:
```
DECODE ERROR: LinkInventoryItem(z): index out of range
Traceback (most recent call last):
  File "/home/cath/src/pyverse/./xtest_en_decoding_all.py", line 39, in <module>
    pkg_back = packet(data=the_bytes)
  File "/home/cath/src/pyverse/pyverse/packet.py", line 35, in __init__
    self.bytes = zerocode.decode(data[6+self.extra_bytes:])
  File "/home/cath/src/pyverse/pyverse/zerocode.py", line 7, in decode
    c = bytedata[i+1] - 1
IndexError: index out of range
```
`pyverse/llTypes.py` is also broken, missing `self.` in a few locations, and in `pyverse/packet.py`the `__bytes__` method is broken because it doesn't include the `result` part as part of what is getting zero-encoded.

Fixing these locally made my bot able to do the group-chat things I tried. I could provide the fixes for all of these, but I understand this project is abandoned and not used by anyone.

**Comment by wjgeorge** [comment]
> I see that this project is abandoned, just filing this so that if someone comes across it like my friend did they don't think this is a working project.
....
> Fixing these locally made my bot able to do the group-chat things I tried. I could provide the fixes for all of these, but I understand this project is abandoned and not used by anyone.

you could make PR with your changes, that way your effort isnt lost
